version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - WEBHOOK_API_KEY=sk_Y7Pq4lyrN8wX66X7Oqla137r8iMKAEkC
    restart: unless-stopped
